/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedMeusIngressosRouteImport } from './routes/_authenticated/meus-ingressos'
import { Route as AuthenticatedPortariaRouteImport } from './routes/_authenticated/portaria'
import { Route as EventosIdRouteImport } from './routes/eventos/$id'
import { Route as FilmesExternalIdRouteImport } from './routes/filmes/$externalId'
import { Route as IngressosPublicIdRouteImport } from './routes/ingressos_.$publicId'
import { Route as AuthenticatedMeusIngressosIdRouteImport } from './routes/_authenticated/meus-ingressos_.$id'
import { Route as AuthenticatedOrganizadorEventosNovoRouteImport } from './routes/_authenticated/organizador/eventos/novo'
import { Route as AuthenticatedPortariaEventIdValidarRouteImport } from './routes/_authenticated/portaria.$eventId.validar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeusIngressosRoute =
  AuthenticatedMeusIngressosRouteImport.update({
    id: '/meus-ingressos',
    path: '/meus-ingressos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortariaRoute = AuthenticatedPortariaRouteImport.update({
  id: '/portaria',
  path: '/portaria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const EventosIdRoute = EventosIdRouteImport.update({
  id: '/eventos/$id',
  path: '/eventos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmesExternalIdRoute = FilmesExternalIdRouteImport.update({
  id: '/filmes/$externalId',
  path: '/filmes/$externalId',
  getParentRoute: () => rootRouteImport,
} as any)
const IngressosPublicIdRoute = IngressosPublicIdRouteImport.update({
  id: '/ingressos_/$publicId',
  path: '/ingressos/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeusIngressosIdRoute =
  AuthenticatedMeusIngressosIdRouteImport.update({
    id: '/meus-ingressos_/$id',
    path: '/meus-ingressos/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizadorEventosNovoRoute =
  AuthenticatedOrganizadorEventosNovoRouteImport.update({
    id: '/organizador/eventos/novo',
    path: '/organizador/eventos/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortariaEventIdValidarRoute =
  AuthenticatedPortariaEventIdValidarRouteImport.update({
    id: '/$eventId/validar',
    path: '/$eventId/validar',
    getParentRoute: () => AuthenticatedPortariaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/meus-ingressos': typeof AuthenticatedMeusIngressosRoute
  '/portaria': typeof AuthenticatedPortariaRouteWithChildren
  '/eventos/$id': typeof EventosIdRoute
  '/filmes/$externalId': typeof FilmesExternalIdRoute
  '/ingressos/$publicId': typeof IngressosPublicIdRoute
  '/meus-ingressos/$id': typeof AuthenticatedMeusIngressosIdRoute
  '/organizador/eventos/novo': typeof AuthenticatedOrganizadorEventosNovoRoute
  '/portaria/$eventId/validar': typeof AuthenticatedPortariaEventIdValidarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/meus-ingressos': typeof AuthenticatedMeusIngressosRoute
  '/portaria': typeof AuthenticatedPortariaRouteWithChildren
  '/eventos/$id': typeof EventosIdRoute
  '/filmes/$externalId': typeof FilmesExternalIdRoute
  '/ingressos/$publicId': typeof IngressosPublicIdRoute
  '/meus-ingressos/$id': typeof AuthenticatedMeusIngressosIdRoute
  '/organizador/eventos/novo': typeof AuthenticatedOrganizadorEventosNovoRoute
  '/portaria/$eventId/validar': typeof AuthenticatedPortariaEventIdValidarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/meus-ingressos': typeof AuthenticatedMeusIngressosRoute
  '/_authenticated/portaria': typeof AuthenticatedPortariaRouteWithChildren
  '/eventos/$id': typeof EventosIdRoute
  '/filmes/$externalId': typeof FilmesExternalIdRoute
  '/ingressos_/$publicId': typeof IngressosPublicIdRoute
  '/_authenticated/meus-ingressos_/$id': typeof AuthenticatedMeusIngressosIdRoute
  '/_authenticated/organizador/eventos/novo': typeof AuthenticatedOrganizadorEventosNovoRoute
  '/_authenticated/portaria/$eventId/validar': typeof AuthenticatedPortariaEventIdValidarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/checkout'
    | '/meus-ingressos'
    | '/portaria'
    | '/eventos/$id'
    | '/filmes/$externalId'
    | '/ingressos/$publicId'
    | '/meus-ingressos/$id'
    | '/organizador/eventos/novo'
    | '/portaria/$eventId/validar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/checkout'
    | '/meus-ingressos'
    | '/portaria'
    | '/eventos/$id'
    | '/filmes/$externalId'
    | '/ingressos/$publicId'
    | '/meus-ingressos/$id'
    | '/organizador/eventos/novo'
    | '/portaria/$eventId/validar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/checkout'
    | '/_authenticated/meus-ingressos'
    | '/_authenticated/portaria'
    | '/eventos/$id'
    | '/filmes/$externalId'
    | '/ingressos_/$publicId'
    | '/_authenticated/meus-ingressos_/$id'
    | '/_authenticated/organizador/eventos/novo'
    | '/_authenticated/portaria/$eventId/validar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  EventosIdRoute: typeof EventosIdRoute
  FilmesExternalIdRoute: typeof FilmesExternalIdRoute
  IngressosPublicIdRoute: typeof IngressosPublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meus-ingressos': {
      id: '/_authenticated/meus-ingressos'
      path: '/meus-ingressos'
      fullPath: '/meus-ingressos'
      preLoaderRoute: typeof AuthenticatedMeusIngressosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portaria': {
      id: '/_authenticated/portaria'
      path: '/portaria'
      fullPath: '/portaria'
      preLoaderRoute: typeof AuthenticatedPortariaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/eventos/$id': {
      id: '/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/eventos/$id'
      preLoaderRoute: typeof EventosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filmes/$externalId': {
      id: '/filmes/$externalId'
      path: '/filmes/$externalId'
      fullPath: '/filmes/$externalId'
      preLoaderRoute: typeof FilmesExternalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingressos_/$publicId': {
      id: '/ingressos_/$publicId'
      path: '/ingressos/$publicId'
      fullPath: '/ingressos/$publicId'
      preLoaderRoute: typeof IngressosPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meus-ingressos_/$id': {
      id: '/_authenticated/meus-ingressos_/$id'
      path: '/meus-ingressos/$id'
      fullPath: '/meus-ingressos/$id'
      preLoaderRoute: typeof AuthenticatedMeusIngressosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizador/eventos/novo': {
      id: '/_authenticated/organizador/eventos/novo'
      path: '/organizador/eventos/novo'
      fullPath: '/organizador/eventos/novo'
      preLoaderRoute: typeof AuthenticatedOrganizadorEventosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portaria/$eventId/validar': {
      id: '/_authenticated/portaria/$eventId/validar'
      path: '/$eventId/validar'
      fullPath: '/portaria/$eventId/validar'
      preLoaderRoute: typeof AuthenticatedPortariaEventIdValidarRouteImport
      parentRoute: typeof AuthenticatedPortariaRoute
    }
  }
}

interface AuthenticatedPortariaRouteChildren {
  AuthenticatedPortariaEventIdValidarRoute: typeof AuthenticatedPortariaEventIdValidarRoute
}

const AuthenticatedPortariaRouteChildren: AuthenticatedPortariaRouteChildren = {
  AuthenticatedPortariaEventIdValidarRoute:
    AuthenticatedPortariaEventIdValidarRoute,
}

const AuthenticatedPortariaRouteWithChildren =
  AuthenticatedPortariaRoute._addFileChildren(
    AuthenticatedPortariaRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedMeusIngressosRoute: typeof AuthenticatedMeusIngressosRoute
  AuthenticatedPortariaRoute: typeof AuthenticatedPortariaRouteWithChildren
  AuthenticatedMeusIngressosIdRoute: typeof AuthenticatedMeusIngressosIdRoute
  AuthenticatedOrganizadorEventosNovoRoute: typeof AuthenticatedOrganizadorEventosNovoRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedMeusIngressosRoute: AuthenticatedMeusIngressosRoute,
  AuthenticatedPortariaRoute: AuthenticatedPortariaRouteWithChildren,
  AuthenticatedMeusIngressosIdRoute: AuthenticatedMeusIngressosIdRoute,
  AuthenticatedOrganizadorEventosNovoRoute:
    AuthenticatedOrganizadorEventosNovoRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  EventosIdRoute: EventosIdRoute,
  FilmesExternalIdRoute: FilmesExternalIdRoute,
  IngressosPublicIdRoute: IngressosPublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
